### ISSUE TITLE
Pod install failure

### ISSUE THREAD

**Issue by Chuongv** [dvor/Antidote#29]
Currently when trying to run pod install, there is an issue with cloning libsodium 1.0.1. However if you bump the toxcore-ios to 0.1.4 the pod install passes, albeit Antidote is not ready for the new toxcore yet.

Not sure if it's worth looking into since we are going to migrate toxcore to a more updated version soon anyways. But if anyone wants to build and look at the app, you can look at this branch as a temporary workaround https://github.com/Chuongv/Antidote/tree/fixlibo

	Installing libsodium 1.0.1 (was 1.0.1)

	[!] Error installing libsodium
	[!] /usr/local/bin/git clone https://github.com/gabriel/libsodium.git /var/folders/xn/vrc0_k3s74j_86hs8b5_vhbh0000gn/T/d20150515-73419-wllqfg --single-branch --depth 1 --branch 1.0.1a

	Cloning into '/var/folders/xn/vrc0_k3s74j_86hs8b5_vhbh0000gn/T/d20150515-73419-wllqfg'...

	warning: Could not find remote branch 1.0.1a to clone.

	fatal: Remote branch 1.0.1a not found in upstream origin

**Comment by dvor** [comment]
Pods are shipped with Antidote, there is no need to run `pod install` to run the app. However, thanks for the fix. :)

**Comment by Chuongv** [comment]
No longer an issue.
